baseURL = "https://da-mir.ru/"
languageCode = "ru"
title = "промышленные вязальные машины Stoll CMS"
theme = "b5-damir"
enableRobotsTXT = true
[menu]
  [[menu.main]]
    name = "Дамир"
    weight = 1
  [[menu.main]]
    parent = "Дамир"
    name = "История компании"
    url = "/istoria-kompanii/"
  [[menu.main]]
    parent = "Дамир"
    name = "Наши партнеры"
    url = "/partnery/"

  [[menu.main]]
    parent = "Дамир"
    name = "Преимущества работы с нами"
    url = "/preimusestva-raboty-s-nami/"
  [[menu.main]]
    name = "Оборудование"
    weight = 2
  [[menu.main]]
    parent = "Оборудование"
    name = "Плосковязальные машины Stoll"
    url = "/oborudovanie/ploskovazalnye-masiny-stoll/"
    weight = 1
  [[menu.main]]
    parent = "Оборудование"
    name = "Оборудование ВТО"
    url = "/oborudovanie/oborudovanie-vto/"
    weight = 2
  [[menu.main]]
    parent = "Оборудование"
    name = "Мотальные машины"
    url = "/oborudovanie/motalnye-masiny/"
    weight = 3
  [[menu.main]]
    parent = "Оборудование"
    name = "Кеттельные машины"
    url = "/oborudovanie/kettelnye-masiny/"
    weight = 4
  [[menu.main]]
    parent = "Оборудование"
    name = "Крутильные машины"
    url = "/oborudovanie/krutilnye-masiny/"
    weight = 5
  [[menu.main]]
    parent = "Оборудование"
    name = "Беечные машины"
    url = "/oborudovanie/beecnye-masiny/"
    weight = 6
  [[menu.main]]
    name = "Сервис STOLL"
    url = "/servis-stoll/"
    weight = 3
  [[menu.main]]
    parent = "Сервис STOLL"
    name = "Восстановленные машины Stoll"
    url = "/servis-stoll/vosstanovlennye-masiny-stoll/"
  [[menu.main]]
    parent = "Сервис STOLL"
    name = "Обучение работе на Stoll"
    url = "/servis-stoll/obucenie-rabote-na-stoll/"
  [[menu.main]]
    parent = "Сервис STOLL"
    name = "Ремонт электроники и механики"
    url = "/servis-stoll/remont-elektroniki-i-mehaniki/"
  [[menu.main]]
    parent = "Сервис STOLL"
    name = "Сервисное обслуживание Stoll"
    url = "/servis-stoll/servisnoe-obsluzivanie-stoll/"
  [[menu.main]]
    name = "Пряжа"
    weight = 4
  [[menu.main]]
    parent = "Пряжа"
    name = "Пряжа на бобинах"
    url = "/pryazha/pryazha-na-bobinakh/"
    weight = 1
  [[menu.main]]
    parent = "Пряжа"
    name = "Вискоза"
    url = "/pryazha/viskoza/"
    weight = 2
  [[menu.main]]
    parent = "Пряжа"
    name = "Марс"
    url = "/pryazha/mars/"
    weight = 3
  [[menu.main]]
    parent = "Пряжа"
    name = "Хлопок/Акрил"
    url = "/pryazha/khlopok-akril/"
    weight = 4
  [[menu.main]]
    parent = "Пряжа"
    name = "Спандекс"
    url = "/pryazha/spandeks/"
    weight = 5
  [[menu.main]]
    parent = "Пряжа"
    name = "Разделительная нить"
    url = "/pryazha/razdelitelnaa-nit/"
    weight = 6
  [[menu.main]]
    parent = "Пряжа"
    name = "Метанит / Люрекс"
    url = "/pryazha/metanit-lureks/"
    weight = 7
  [[menu.main]]
    name = "Каталог"
    url = "/katalog/"
    weight = 5
  [[menu.main]]
    name = "Трикотажная фабрика"
    weight = 6
  [[menu.main]]
    parent = "Трикотажная фабрика"
    name = "О трикотажной фабрике"
    url = "/o-trikotaznoi-fabrike/"
    weight = 1
  [[menu.main]]
    parent = "Трикотажная фабрика"
    name = "Каталог изделий"
    url = "/katalog-izdeliy/"
  [[menu.main]]
    name = "Контакты"
    url = "/kontakty/"
    weight = 7
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.css]
      keepCSS2 = true
      precision = 0
    [minify.tdewolff.html]
      keepComments = false
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = false
    [minify.tdewolff.js]
      keepVarNames = false
      precision = 0
    [minify.tdewolff.json]
      precision = 0
    [minify.tdewolff.svg]
      precision = 0
    [minify.tdewolff.xml]
      keepWhitespace = false