baseURL = "http://da-mir.ru/"
languageCode = "ru"
title = "промышленные вязальные машины Stoll CMS"
theme = "botstrp5-busns"

[menu]
  [[menu.main]]
    name = "Дамир"
    weight = 1
  [[menu.main]]
    parent = "Дамир"
    name = "История компании"
    url = "/istoria-kompanii/"

  [[menu.main]]
    parent = "Дамир"
    name = "Преимущества работы с нами"
    url = "/preimusestva-raboty-s-nami/"
  [[menu.main]]
    name = "Оборудование"
    weight = 2
  [[menu.main]]
    parent = "Оборудование"
    name = "Плосковязальные машины Stoll"
    url = "/oborudovanie/ploskovazalnye-masiny-stoll/"
  [[menu.main]]
    parent = "Оборудование"
    name = "Оборудование ВТО"
    url = "/oborudovanie/oborudovanie-vto/"
  [[menu.main]]
    parent = "Оборудование"
    name = "Мотальные машины"
    url = "/oborudovanie/motalnye-masiny/"
  [[menu.main]]
    parent = "Оборудование"
    name = "Кеттельные машины"
    url = "/oborudovanie/kettelnye-masiny/"
  [[menu.main]]
    parent = "Оборудование"
    name = "Крутильные машины"
    url = "/oborudovanie/krutilnye-masiny/"
  [[menu.main]]
    parent = "Оборудование"
    name = "Беечные машины"
    url = "/oborudovanie/beecnye-masiny/"
  [[menu.main]]
    name = "Сервис STOLL"
    url = "/servis-stoll/"
    weight = 3
  [[menu.main]]
    parent = "Сервис STOLL"
    name = "Восстановленные машины Stoll"
    url = "/servis-stoll/vosstanovlennye-masiny-stoll/"
  [[menu.main]]
    parent = "Сервис STOLL"
    name = "Обучение работе на Stoll"
    url = "/servis-stoll/obucenie-rabote-na-stoll/"
  [[menu.main]]
    parent = "Сервис STOLL"
    name = "Ремонт электроники и механики"
    url = "/servis-stoll/remont-elektroniki-i-mehaniki/"
  [[menu.main]]
    parent = "Сервис STOLL"
    name = "Сервисное обслуживание Stoll"
    url = "/servis-stoll/servisnoe-obsluzivanie-stoll/"
  [[menu.main]]
    name = "Пряжа"
    weight = 4
  [[menu.main]]
    parent = "Пряжа"
    name = "Пряжа на бобинах"
    url = "/pryazha/pryazha-na-bobinakh/"
  [[menu.main]]
    parent = "Пряжа"
    name = "Вискоза"
    url = "/pryazha/viskoza/"
  [[menu.main]]
    parent = "Пряжа"
    name = "Марс"
    url = "/pryazha/mars/"
  [[menu.main]]
    parent = "Пряжа"
    name = "Хлопок/Акрил"
    url = "/pryazha/khlopok-akril/"
  [[menu.main]]
    parent = "Пряжа"
    name = "Спандекс"
    url = "/pryazha/spandeks/"
  [[menu.main]]
    parent = "Пряжа"
    name = "Разделительная нить"
    url = "/pryazha/razdelitelnaa-nit/"
  [[menu.main]]
    parent = "Пряжа"
    name = "Метанит / Люрекс"
    url = "/pryazha/metanit-lureks/"
  [[menu.main]]
    name = "Каталог"
    url = "/katalog/"
    weight = 5
  [[menu.main]]
    name = "Трикотажная фабрика"
    weight = 6
  [[menu.main]]
    parent = "Трикотажная фабрика"
    name = "О трикотажной фабрике"
    url = "/o-trikotaznoi-fabrike/"
  [[menu.main]]
    parent = "Трикотажная фабрика"
    name = "Каталог изделий"
    url = "/katalog-izdeliy/"
  [[menu.main]]
    name = "Контакты"
    url = "/kontakty/"
    weight = 7
